# Stage 1: NVIDIA CUDA base image with cuDNN
FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu18.04 as cuda-base

# Stage 2: Start with the custom yangyangfu/jmodelica_py3 base image
FROM yangyangfu/jmodelica_py3
LABEL maintainer="yangyangfu(yangyang.fu@tamu.edu)"

# arch
ENV NVARCH x86_64

# Set CUDA and cuDNN environment variables
ENV CUDA_HOME /usr/local/cuda
ENV PATH /usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:${LD_LIBRARY_PATH}

# root 
USER root

# Install Python libraries and tools
RUN conda update conda && \
    conda config --add channels conda-forge && \
    conda install pip \
    scikit-learn \
    seaborn \
    tianshou=0.4.11 \
    matplotlib=3.3.2 \
    pvlib-python=0.9.1 \
    setuptools=59.1.1 \
    numpy=1.22.3 \
    ray-tune=1.10.0 && \
    conda clean -ya

RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117

# Fix a broken link
RUN rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6 && \
    ln -s /opt/conda/lib/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

# Install additional Python packages
WORKDIR $HOME 
RUN pip install casadi==3.5.5 pymoo==0.6.0

# Install fmu-gym
WORKDIR $HOME
RUN git config --global url."https://github.com/".insteadOf git://github.com/ && \
    pip install git+git://github.com/YangyangFu/modelicagym.git@master 

# Install customized gym environment
# Single zone damper control environment
WORKDIR $HOME
RUN mkdir github
COPY ./testcases/gym-environments/single-zone/gym_singlezone_jmodelica $HOME/github/testcases/gym-environments/single-zone/gym_singlezone_jmodelica
COPY ./testcases/gym-environments/single-zone/setup.py $HOME/github/testcases/gym-environments/single-zone/setup.py
RUN cd $HOME/github/testcases/gym-environments/single-zone && pip install -e .

# Install Modelica dependency
COPY ./library /usr/local/JModelica/ThirdParty/MSL

# Switch back to developer user
USER developer
WORKDIR $HOME 

# Matplotlib font cache
RUN python -c "import matplotlib.pyplot"
