FROM yangyangfu/jmodelica_py3
LABEL maintainer yangyangfu(yangyang.fu@tamu.edu)

# root 
USER root

# update: for pytorch cpu/gpu - no need if no render
# RUN apt-get update && \
#    apt-get install -y --no-install-recommends \
#    python-opengl 

### ====================================================================================
## install env for OPC: optimizer, nonlinear system identifier
RUN conda update conda && \
    conda config --add channels conda-forge && \
    conda install pip \
         scikit-learn \
         casadi \
         tianshou \
         matplotlib \
         pvlib-python \
         joblib && \
    conda clean -ya

## install fmu-gym
WORKDIR $HOME
RUN pip install git+git://github.com/YangyangFu/modelicagym.git@master 

### =======================================================================================
### intall customized gym environment into docker: install a building control environment
# install single zone damper control environment
WORKDIR $HOME
RUN mkdir github
COPY ./testcases/gym-environments/single-zone/gym_singlezone_jmodelica $HOME/github/testcases/gym-environments/single-zone/gym_singlezone_jmodelica
COPY ./testcases/gym-environments/single-zone/setup.py $HOME/github/testcases/gym-environments/single-zone/setup.py
RUN cd $HOME/github/testcases/gym-environments/single-zone && pip install -e .

# install single zone temperature control environment
WORKDIR $HOME
COPY ./testcases/gym-environments/single-zone-temperature/gym_singlezone_temperature $HOME/github/testcases/gym-environments/single-zone-temperature/gym_singlezone_temperature
COPY ./testcases/gym-environments/single-zone-temperature/setup.py $HOME/github/testcases/gym-environments/single-zone-temperature/setup.py
RUN cd $HOME/github/testcases/gym-environments/single-zone-temperature && pip install -e .

# install five zone supervisory control environment
WORKDIR $HOME
COPY ./testcases/gym-environments/five-zones/gym_fivezone_jmodelica $HOME/github/testcases/gym-environments/five-zones/gym_fivezone_jmodelica
COPY ./testcases/gym-environments/five-zones/setup.py $HOME/github/testcases/gym-environments/five-zones/setup.py
RUN cd $HOME/github/testcases/gym-environments/five-zones && pip install -e .


### ===========================================================================================
### install testcase dependency
# install Modelica dependency
COPY ./library /usr/local/JModelica/ThirdParty/MSL

### =============================
USER developer
WORKDIR $HOME 
# Avoid warning that Matplotlib is building the font cache using fc-list. This may take a moment.
# This needs to be towards the end of the script as the command writes data to
# /home/developer/.cache
RUN python -c "import matplotlib.pyplot"