# discret action space
from gym_singlezone_temperature.envs import single_zone_temperature_v0
from gym_singlezone_temperature.envs import single_zone_temperature_v1
# continuous action space
from gym_singlezone_temperature.envs import single_zone_temperature_v2